//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Estimation_Software {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model_Estimation_Software.ResEn", typeof(ResEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Borrar_Todo {
            get {
                return ResourceManager.GetString("Borrar Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams per model.
        /// </summary>
        internal static string CantG {
            get {
                return ResourceManager.GetString("CantG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of models.
        /// </summary>
        internal static string CantModel {
            get {
                return ResourceManager.GetString("CantModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Datos {
            get {
                return ResourceManager.GetString("Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        internal static string Est {
            get {
                return ResourceManager.GetString("Est", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string Estimar {
            get {
                return ResourceManager.GetString("Estimar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Lenguaje {
            get {
                return ResourceManager.GetString("Lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for every 30 min.
        /// </summary>
        internal static string pc30m {
            get {
                return ResourceManager.GetString("pc30m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string Pers {
            get {
                return ResourceManager.GetString("Pers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string Por {
            get {
                return ResourceManager.GetString("Por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for 3 grams.
        /// </summary>
        internal static string pp3g {
            get {
                return ResourceManager.GetString("pp3g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per model.
        /// </summary>
        internal static string Ppm {
            get {
                return ResourceManager.GetString("Ppm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to printing time hours.
        /// </summary>
        internal static string TimeImpH {
            get {
                return ResourceManager.GetString("TimeImpH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to printing time minutes.
        /// </summary>
        internal static string TimeImpMin {
            get {
                return ResourceManager.GetString("TimeImpMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
    }
}
